apiVersion: skaffold/v3
kind: Config
metadata:
  name: test-app
build:  
  tagPolicy:
    sha256: {}
  artifacts:
  - image: fooddelivery-restaurants-service
    context: ./
    
    docker:
      noCache: false
      dockerfile: ./services/Restaurants/Infra/Dockerfile.dev
     
    sync:
      infer:
        - "services/Restaurants/**/*.cs"
        - "contracts/**/*.cs"
        - "services/Shared/**/*.cs"
        - "**/*.json"
      
  local:
      push: false
      useBuildkit: true
manifests:
  rawYaml:
    - ./services/Restaurants/Infra/secrets.yml
    - ./services/Restaurants/Infra/pg.yml
    - ./infra/kafka.yml
    - ./services/Restaurants/Infra/backend.yml
            
deploy:
  kubectl: {}