apiVersion: skaffold/v3
kind: Config
metadata:
  name: clusters

manifests:
  rawYaml: []

profiles:
  - name: kafka
    manifests:
      rawYaml:
        - ./infra/kafka.yml
  - name: ingress
    manifests:
      rawYaml:
        - ./infra/ingress.yml
  - name: ingress-config
    manifests:
      rawYaml:
        - ./infra/ingress-config.yml
  - name: redis
    manifests:
      rawYaml:
        - ./infra/redis.yml
  - name: seq-secrets
    manifests:
      rawYaml:
        - ./infra/seq-secrets.yml
  - name: seq
    manifests:
      rawYaml:
        - ./infra/seq.yml
  - name: all
    manifests:
      rawYaml:
        - ./infra/kafka.yml
        - ./infra/ingress.yml
        - ./infra/redis.yml
        - ./infra/seq-secrets.yml
        - ./infra/seq.yml
        - ./infra/ingress-config.yml
     
deploy:
  kubectl: {}