apiVersion: skaffold/v3
kind: Config
metadata:
  name: services
build:  
  tagPolicy:
    gitCommit: {}
  artifacts:
    # - image: fooddelivery-restaurants-service
    #   context: ./
    #   docker:
    #     noCache: false
    #     dockerfile: ./services/Restaurants/Infra/Dockerfile.dev
    #   sync:
    #     infer:
    #       - "services/**/*.cs"
    #       - "**/*.json"
    #       - "**/*.yml"

    - image: fooddelivery-auth-service
      context: ./
      docker:
        noCache: true
        dockerfile: ./services/Auth/Infra/Dockerfile.dev
      sync:
        infer:
          - "services/**/*.cs"
          - "**/*.json"
          - "**/*.yml"

  local:
      push: false
      useBuildkit: true

manifests:
  rawYaml:
    # # Restaurants service
    # - ./services/Restaurants/Infra/backend-secrets.yml
    # - ./services/Restaurants/Infra/backend.yml

    # Auth service
    - ./services/Auth/Infra/backend-secrets.yml
    - ./services/Auth/Infra/backend.yml
            
deploy:
  kubectl: 
    defaultNamespace: kafka