apiVersion: skaffold/v3
kind: Config
metadata:
  name: clusters

manifests:
  rawYaml:
    - ./infra/kafka.yml
    - ./infra/ingress.yml
    - ./infra/redis.yml
    - ./infra/seq-secrets.yml
    - ./infra/seq.yml
     
deploy:
  kubectl: {}