apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: kafka
  labels:
    name: api-gateway
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: "/api/restaurants"
        pathType: Prefix
        backend:
          service:
            name: restaurants-service
            port:
              number: 8080
      - path: "/api/auth"
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 8080

      - path: "/api/users"
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 8080