apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: kafka
spec:
  selector:
    app: auth-depl
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: auth-depl
  template:
    metadata:
      labels:
        app: auth-depl
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z auth-db-rw 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
        - name: wait-for-kafka
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z my-cluster-kafka-bootstrap 9092; do echo "waiting for kafka..."; sleep 2; done;']
      containers:
      - name: auth-depl
        image: fooddelivery-auth-service:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 35
        readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 35
        
        env:
          - name: Kafka__BootstrapServers
            value: "my-cluster-kafka-bootstrap:9092"
          - name: Seq
            value: "http://seq-service:5341"
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ConnectionStrings__DefaultConnection"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "ConnectionStrings__DefaultConnection"
          - name: "ConnectionStrings__REDIS"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "ConnectionStrings__REDIS"
          - name: "JwtSettings__AccessTokenExpirationMinutes"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "JwtSettings__AccessTokenExpirationMinutes"
          - name: "JwtSettings__Audience"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "JwtSettings__Audience"
          - name: "JwtSettings__Issuer"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "JwtSettings__Issuer"
          - name: "JwtSettings__SecretKey"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "JwtSettings__SecretKey"
          - name: "JwtSettings__RefreshTokenExpirationDays"
            valueFrom:
              secretKeyRef:
                name: "backend-auth-secret"
                key: "JwtSettings__RefreshTokenExpirationDays"
                
          - name: "ASPNETCORE_URLS"
            value: "http://+:8080"
          - name: "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT"
            value: "false"

        ports:
        - containerPort: 8080
