FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine

WORKDIR /app

COPY Directory.Packages.props ./
COPY Directory.Build.props ./
COPY contracts/Shared.Contracts/Shared.Contracts.csproj ./contracts/Shared.Contracts/
COPY contracts/Restaurants.Contracts/Restaurants.Contracts.csproj ./contracts/Restaurants.Contracts/
COPY contracts/Auth.Contracts/Auth.Contracts.csproj ./contracts/Auth.Contracts/

COPY services/Shared/Shared.csproj ./services/Shared/
COPY services/Restaurants/Restaurants.csproj ./services/Restaurants/

RUN apk add --no-cache icu-libs
RUN dotnet restore services/Restaurants/Restaurants.csproj

COPY contracts/Shared.Contracts/ ./contracts/Shared.Contracts/
COPY contracts/Restaurants.Contracts/ ./contracts/Restaurants.Contracts/
COPY contracts/Auth.Contracts/ ./contracts/Auth.Contracts/

COPY services/Shared/ ./services/Shared/
COPY services/Restaurants/ ./services/Restaurants/

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--no-hot-reload", "--project", "services/Restaurants/Restaurants.csproj"]